#!/usr/bin/env node
// Dev server for Dwarf/library-slice.
// Serves all static files + handles POST /save-labels from tile-labeler.html.
// Usage: node server.js        (default port 8080)
//        node server.js 3000   (custom port)

const http = require('http');
const fs   = require('fs');
const path = require('path');

const PORT    = parseInt(process.argv[2]) || 8080;
const ROOT    = __dirname;
const LABELS_FILE = path.join(ROOT, 'engine', 'tiles-labeler.js');

const MIME = {
  '.html': 'text/html',
  '.js':   'application/javascript',
  '.css':  'text/css',
  '.png':  'image/png',
  '.jpg':  'image/jpeg',
  '.json': 'application/json',
  '.ico':  'image/x-icon',
};

const LABEL_COLORS = {
  GRASS: '#536c2a', SAND: '#cec284', STONE: '#737373', WOOD: '#66381a',
};

function generateJS(data) {
  const { sheet, tileSize, selections } = data;
  const fn = tileSize === 16 ? 'T16' : 'T';
  const lines = [
    '// Auto-generated by tile-labeler — do not edit by hand.',
    '// Re-paint in tile-labeler.html to update.',
    '(function() {',
  ];
  for (const [label, keys] of Object.entries(selections)) {
    if (!keys.length) continue;
    const baseKey = `F_${label}`;
    const variantKeys = keys.map((_, i) =>
      i === 0 ? baseKey : `${baseKey}_${String.fromCharCode(64 + i)}`
    );
    const color = LABEL_COLORS[label] || '#888888';
    keys.forEach((k, i) => {
      const [c, r] = k.split(',').map(Number);
      lines.push(`  TILES['${variantKeys[i]}'] = ${fn}('${sheet}', ${c}, ${r}, false, '${color}');`);
    });
    lines.push(`  FLOOR_VARIANTS['${baseKey}'] = [${variantKeys.map(k => `'${k}'`).join(', ')}];`);
  }
  lines.push('})();');
  return lines.join('\n') + '\n';
}

const OLLAMA = { host: '127.0.0.1', port: 11434 };

function proxyOllama(req, res, path) {
  let body = '';
  req.on('data', d => body += d);
  req.on('end', () => {
    const opts = { host: OLLAMA.host, port: OLLAMA.port, path, method: req.method,
      headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) } };
    const proxy = http.request(opts, pr => {
      const hdrs = { 'Access-Control-Allow-Origin': '*' };
      if (pr.headers['content-type']) hdrs['Content-Type'] = pr.headers['content-type'];
      res.writeHead(pr.statusCode, hdrs);
      pr.pipe(res);
    });
    proxy.on('error', () => { res.writeHead(502); res.end('{"error":"ollama unreachable"}'); });
    proxy.write(body);
    proxy.end();
  });
}

const server = http.createServer((req, res) => {
  if (req.method === 'POST' && req.url.startsWith('/ollama/')) {
    proxyOllama(req, res, req.url.replace('/ollama', ''));
    return;
  }

  if (req.method === 'POST' && req.url === '/save-labels') {
    let body = '';
    req.on('data', d => body += d);
    req.on('end', () => {
      try {
        const data = JSON.parse(body);
        const js = generateJS(data);
        fs.writeFileSync(LABELS_FILE, js);
        res.writeHead(200, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ ok: true }));
        console.log(`[labeler] saved ${Object.values(data.selections).flat().length} tiles → engine/tiles-labeler.js`);
      } catch (e) {
        res.writeHead(400);
        res.end(e.message);
      }
    });
    return;
  }

  let filePath = path.join(ROOT, req.url === '/' ? 'index.html' : req.url);
  // Strip query strings
  filePath = filePath.split('?')[0];

  fs.readFile(filePath, (err, data) => {
    if (err) {
      res.writeHead(404);
      res.end('Not found');
      return;
    }
    const ext = path.extname(filePath);
    res.writeHead(200, { 'Content-Type': MIME[ext] || 'application/octet-stream' });
    res.end(data);
  });
});

server.listen(PORT, () => {
  console.log(`Dwarf dev server running at http://localhost:${PORT}`);
  console.log(`  Game:         http://localhost:${PORT}/`);
  console.log(`  Tile labeler: http://localhost:${PORT}/tile-labeler.html`);
});
