// Auto-generated by tile-labeler
(function() {
  TILES['F_GRASS'] = T16('terrain', 4, 0, false, '#536c2a');
  TILES['F_GRASS_A'] = T16('terrain', 5, 0, false, '#536c2a');
  TILES['F_GRASS_B'] = T16('terrain', 4, 1, false, '#536c2a');
  TILES['F_GRASS_C'] = T16('terrain', 5, 1, false, '#536c2a');
  TILES['F_GRASS_D'] = T16('terrain', 4, 2, false, '#536c2a');
  TILES['F_GRASS_E'] = T16('terrain', 5, 2, false, '#536c2a');
  TILES['F_GRASS_F'] = T16('terrain', 4, 3, false, '#536c2a');
  TILES['F_GRASS_G'] = T16('terrain', 5, 3, false, '#536c2a');
  FLOOR_VARIANTS['F_GRASS'] = ['F_GRASS', 'F_GRASS_A', 'F_GRASS_B', 'F_GRASS_C', 'F_GRASS_D', 'F_GRASS_E', 'F_GRASS_F', 'F_GRASS_G'];
})();
