// Auto-generated by tile-labeler — do not edit by hand.
// Re-paint in tile-labeler.html to update.
(function() {
  TILES['F_WOOD'] = T16('interior', 12, 0, false, '#66381a');
  TILES['F_WOOD_A'] = T16('interior', 11, 0, false, '#66381a');
  FLOOR_VARIANTS['F_WOOD'] = ['F_WOOD', 'F_WOOD_A'];
})();
